export const LOAD_MUNTEN_SUCCESS = "LOAD_MUNTEN_SUCCESS";
export const LOAD_AANDELEN_SUCCESS = "LOAD_AANDELEN_SUCCESS";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS= "LOGOUT_USER_SUCCESS";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const REMOVE_FAV_SUCCESS = "REMOVE_FAV_SUCCESS";
export const ADD_FAV_SUCCESS = "ADD_FAV_SUCCESS";